name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
      
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
  
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Download arm64-v8a-debug APK
        uses: actions/upload-artifact@v4
        with:
          name: ds-arm64-v8a-debug
          path: ./app/build/outputs/apk/debug/app-arm64-v8a-debug.apk

      - name: Download armeabi-v7a-debug APK
        uses: actions/upload-artifact@v4
        with:
          name: ds-armeabi-v7a-debug
          path: ./app/build/outputs/apk/debug/app-armeabi-v7a-debug.apk

      - name: Download x86-debug APK
        uses: actions/upload-artifact@v4
        with:
          name: ds-x86-debug
          path: ./app/build/outputs/apk/debug/app-x86-debug.apk

      - name: Download x86_64-debug APK
        uses: actions/upload-artifact@v4
        with:
          name: ds-x86_64-debug
          path: ./app/build/outputs/apk/debug/app-x86_64-debug.apk

      - name: Download universal-debug APK
        uses: actions/upload-artifact@v4
        with:
          name: ds-universal-debug
          path: ./app/build/outputs/apk/debug/app-universal-debug.apk